version: "3.9"

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - storedb:/var/lib/postgresql
volumes:
  storedb: