# Generated by Django 4.0.6 on 2022-07-20 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod_and_cat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='category',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='product',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='prod_and_cat.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristics',
            field=models.JSONField(blank=True),
        ),
    ]
